name: remarkable
favicon: null
layout_spectrum: 0.403707901481539
typography_spectrum: 0.50752
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.10733509063720703
  saturation: 0.4028655788861215
  rhythmicContrast: 0.6412872613873333
purpose: []
